### ISSUE TITLE
unable to import mmcif.io.IoAdapterCore

### ISSUE THREAD

**Issue by cypreeti** [rcsb/py-mmcif#3]
Hi,

I installed mmcif module with python3 environment. It installs without any error but I am unable to mmcif.io.IoAdapterCore. 
I get the following error:

>>> import mmcif.io.IoAdapterCore
Traceback (most recent call last):
  File "/nfs/msd/work2/cypreeti/onedep_python3_venv/lib/python3.6/site-packages/mmcif/io/IoAdapterCore.py", line 56, in <module>
    from mmcif.core.mmciflib import ParseCifSimple, CifFile, ParseCifSelective, CifFileReadDef
ImportError: /nfs/msd/work2/cypreeti/onedep_python3_venv/lib/python3.6/site-packages/mmcif/core/mmciflib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyThread_tss_get

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/msd/work2/cypreeti/onedep_python3_venv/lib/python3.6/site-packages/mmcif/io/IoAdapterCore.py", line 60, in <module>
    from build.lib.mmciflib import ParseCifSimple, CifFile, ParseCifSelective, PdbxType, CifFileReadDef
ModuleNotFoundError: No module named 'build'

Can you suggest, how can I resolve this issue.
Thanks
Regards
Preeti

**Comment by cypreeti** [comment]
works with python 3.7.2
